services:
  - name: Spotify-Wrapped
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Spotify-Wrapped.wsgi:application"
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: "Spotify-Wrapped.settings"
