# Generated by Django 5.1.1 on 2024-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
