# Generated by Django 5.1.1 on 2024-12-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_spotify_refresh_token_profile_spotify_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wrap_type', models.CharField(max_length=50)),
                ('wrap_data', models.JSONField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_wraps', to='authentication.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
