# Generated by Django 5.1.3 on 2024-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsong',
            name='months',
        ),
        migrations.AddField(
            model_name='topsong',
            name='spotify_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topsong',
            name='snippet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
